author: '乌啦啦 & 碎碎念'
title: 呜啦啦的碎碎念
subtitle: 眼中有世界，心中有天地
description: 心有猛虎，细嗅蔷薇
welcome_message: 欢迎来到我的个人站~
baidu_analytics: a505b5ee255ed40e25e240605e8b588b
repository_url: https://github.com/actors315/actors315.github.io
avatarTitle: actors315
avatarDesc: 一个爱思考的行动者

authorList:
  actors315: 呜啦啦
  Aimme: 碎碎念

nav:
  - {title: 技术博客, description: '乌啦啦的碎碎念', url: '/blog/'}
  - {title: 心情随笔, description: '心情随笔', url: '/essay/'}
  - {title: 关于我, description: '关于我', url: '/about'}

rss: false

contact:
  - {title: '@actors315 的Github', url: 'https://github.com/actors315', icon: '/assets/images/github.png' }
  - {title: '@橙子橙子我是大头', url: 'https://weibo.com/tiancaidatou', icon: '/assets/images/weibo.png' }
  - {title: '@actors315 的邮箱', url: 'mailto:actors315@gmail.com', icon: '/assets/images/email.png' }
  - {title: '@呜啦啦的碎碎念', url: '', hover: '/assets/images/qrcode_for_gh_70d3df3ad2c4_258.jpg', icon: '/assets/images/wechat.png'}

repositories:
  - {'title': 'twinkle/di',description: '基于 PSR-11 的简单DI实现',url: 'https://github.com/actors315/DI'}
  - {'title': 'lingyin/ethereum-address',description: '简单较验ETH地址的合法性',url: 'https://github.com/actors315/ethereum-address'}

exclude: ["application","bin","vendor","blog/page.html"]

url: "https://blog.xiehuanjin.cn"
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "essay/page:num"
defaults:
  scope:
    path: "google119f7a85c4f8f713.html"
  values:
    sitemap: false