author: '乌啦啦 & 碎碎念'
title: 呜啦啦的碎碎念
subtitle: 眼中有世界，心中有天地
description: 心有猛虎，细嗅蔷薇
welcome_message: 欢迎来到我的个人站~
baidu_analytics: a505b5ee255ed40e25e240605e8b588b
repository_url: https://github.com/actors315/actors315.github.io
avatarTitle: actors315
avatarDesc: 一个爱思考的行动者

authorList:
    actors315: 呜啦啦
    Aimme: 碎碎念

nav:
    - {title: 技术博客, description: '乌啦啦的碎碎念', url: '/blog/'}
    - {title: 心情随笔, description: '心情随笔', url: '/essay/'}
    - {title: 关于我, description: '关于我', url: '/about'}

rss: false

contact:
    - {title: '@actors315 的Github', url: 'https://github.com/actors315', icon: '/assets/images/github.png' }
    - {title: '@橙子橙子我是大头', url: 'https://weibo.com/tiancaidatou', icon: '/assets/images/weibo.png' }
    - {title: '@actors315 的邮箱', url: 'mailto:actors315@gmail.com', icon: '/assets/images/email.png' }

exclude: ["application","bin","vendor","blog/page.html"]

plugins: [jekyll-paginate]
paginate: 20
paginate_path: "essay/page:num"