author: '呜啦啦 & 碎碎念'
title: 呜啦啦的碎碎念
subtitle: 眼中有世界，心中有天地
description: 心有猛虎，细嗅蔷薇
baidu_analytics: a505b5ee255ed40e25e240605e8b588b
repository_url: https://github.com/actors315/actors315.github.io
avatarTitle: actors315
avatarDesc: 一个小学生

authorList:
    actors315: 呜啦啦
    Aimme: 碎碎念

nav:
    - {title: 技术博客, description: blog, url: '/blog/'}
    - {title: 心情随笔, description: essay, url: '/essay/'}
    - {title: 关于我, description: about, url: '/about'}

rss: false

contact:
    - {title: '@actors315 的Github', url: 'https://github.com/actors315', icon: '/assets/images/github.png' }
    - {title: '@橙子橙子我是大头', url: 'https://weibo.com/tiancaidatou', icon: '/assets/images/weibo.png' }
    - {title: '@actors315 的邮箱', url: 'mailto:actors315@gmail.com', icon: '/assets/images/email.png' }

exclude: ["application","bin","vendor","blog/page.html"]

plugins: [jekyll-paginate]
paginate: 20
paginate_path: "essay/page:num"